services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: gemmy-kafka-cluster
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - /var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "echo 'true'"]
      interval: 8s

  btcusd:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      kafka:
        condition: service_healthy