// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FillOrderData {
    #[prost(bytes = "vec", tag = "1")]
    pub order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub matched_order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "OrderSide", tag = "3")]
    pub taker_side: i32,
    #[prost(uint64, tag = "4")]
    pub price: u64,
    #[prost(uint64, tag = "5")]
    pub amount: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrder {
    #[prost(enumeration = "OrderStatus", tag = "1")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub price: u64,
    #[prost(uint64, tag = "4")]
    pub quantity: u64,
    #[prost(enumeration = "OrderSide", tag = "5")]
    pub side: i32,
    #[prost(string, tag = "6")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub timestamp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FillOrder {
    #[prost(enumeration = "OrderStatus", tag = "1")]
    pub status: i32,
    #[prost(message, repeated, tag = "2")]
    pub filled_orders: ::prost::alloc::vec::Vec<FillOrderData>,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub timestamp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartialFillOrder {
    #[prost(enumeration = "OrderStatus", tag = "1")]
    pub status: i32,
    #[prost(message, optional, tag = "2")]
    pub partial_create: ::core::option::Option<CreateOrder>,
    #[prost(message, optional, tag = "3")]
    pub partial_fills: ::core::option::Option<FillOrder>,
    #[prost(string, tag = "4")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub timestamp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelModifyOrder {
    #[prost(enumeration = "OrderStatus", tag = "1")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub timestamp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenericMessage {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub timestamp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RfqResult {
    #[prost(enumeration = "RfqStatus", tag = "1")]
    pub status: i32,
    #[prost(uint64, tag = "2")]
    pub price: u64,
    #[prost(uint64, tag = "3")]
    pub quantity: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateLimitOrderRequest {
    #[prost(uint64, tag = "1")]
    pub price: u64,
    #[prost(uint64, tag = "2")]
    pub quantity: u64,
    #[prost(enumeration = "OrderSide", tag = "3")]
    pub side: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateMarketOrderRequest {
    #[prost(uint64, tag = "1")]
    pub quantity: u64,
    #[prost(enumeration = "OrderSide", tag = "2")]
    pub side: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModifyLimitOrderRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub order_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub price: u64,
    #[prost(uint64, tag = "3")]
    pub quantity: u64,
    #[prost(enumeration = "OrderSide", tag = "4")]
    pub side: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelLimitOrderRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub order_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OrderbookDataRequest {
    #[prost(enumeration = "Granularity", tag = "1")]
    pub granularity: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Level {
    #[prost(uint64, tag = "1")]
    pub price: u64,
    #[prost(uint64, tag = "2")]
    pub quantity: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderbookData {
    #[prost(uint64, tag = "1")]
    pub max_bid: u64,
    #[prost(uint64, tag = "2")]
    pub min_ask: u64,
    #[prost(uint64, tag = "3")]
    pub last_trade_price: u64,
    #[prost(message, repeated, tag = "4")]
    pub bids: ::prost::alloc::vec::Vec<Level>,
    #[prost(message, repeated, tag = "5")]
    pub asks: ::prost::alloc::vec::Vec<Level>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderSide {
    Bid = 0,
    Ask = 1,
}
impl OrderSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bid => "Bid",
            Self::Ask => "Ask",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Bid" => Some(Self::Bid),
            "Ask" => Some(Self::Ask),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderStatus {
    Created = 0,
    Filled = 1,
    PartiallyFilled = 2,
    Modified = 3,
    Cancelled = 4,
}
impl OrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Created => "Created",
            Self::Filled => "Filled",
            Self::PartiallyFilled => "PartiallyFilled",
            Self::Modified => "Modified",
            Self::Cancelled => "Cancelled",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Created" => Some(Self::Created),
            "Filled" => Some(Self::Filled),
            "PartiallyFilled" => Some(Self::PartiallyFilled),
            "Modified" => Some(Self::Modified),
            "Cancelled" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RfqStatus {
    CompleteFill = 0,
    PartialFill = 1,
    ConvertLimit = 2,
    NotPossible = 3,
}
impl RfqStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CompleteFill => "CompleteFill",
            Self::PartialFill => "PartialFill",
            Self::ConvertLimit => "ConvertLimit",
            Self::NotPossible => "NotPossible",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CompleteFill" => Some(Self::CompleteFill),
            "PartialFill" => Some(Self::PartialFill),
            "ConvertLimit" => Some(Self::ConvertLimit),
            "NotPossible" => Some(Self::NotPossible),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Granularity {
    P00 = 0,
    P0 = 1,
    P = 2,
    P10 = 3,
    P100 = 4,
}
impl Granularity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::P00 => "P00",
            Self::P0 => "P0",
            Self::P => "P",
            Self::P10 => "P10",
            Self::P100 => "P100",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "P00" => Some(Self::P00),
            "P0" => Some(Self::P0),
            "P" => Some(Self::P),
            "P10" => Some(Self::P10),
            "P100" => Some(Self::P100),
            _ => None,
        }
    }
}
